### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by pgk**
`sensei_lesson_single_meta ` is deprecated as of sensei 1.9.0

### CODE REVIEW

**Comment by bor0** [comment]
Need to investigate why, but after this change, subscribers can see media for lessons that are not yet available:
screen shot 2016-11-16 at 16 31 50

Not sure if we need to add the check as part of `Sensei_Media_Attachments::display_attached_media` or SCD.

**Comment by pgk** [comment]
refs #13

**Comment by jtsternberg** [comment]
Any progress here? Our debug.log is cluttering up with these notices. Would love to know if an update is on the horizon.

**Comment by donnapep** [comment]
Closing as duplicate of PR #20.

**Pull request closed without merging**
